### ISSUE TITLE
Some feature requests?

### ISSUE THREAD

**Issue by ralutris** [Dangry98/Key-Ops-Toolkit#1]
1. Click to select + drag to adjust + drag to select in blank space

Polyquilt imitates this, but there is no independent (select + adjust) function.

It is packed into the main tool together with the surface creation function. It is easy to create points, lines and surfaces by mistake, and it cannot be used as a select + adjustment tool. An independent function should be added.

2. The size of the selection judgment range (hitbox?) should be adjustable

Blender's selection judgment range is too large, and it is really difficult to select accurately.

Selection + adjustment is barely achieved through the plug-in power select.

But it is found that the wrong selection always occurs in the air. Clicking or dragging in the blank space always selects the points, lines and surfaces far away.  After searching…

(https://blenderartists.org/t/object-selection-accuracy/689986/
/8 The related function found by the poster. The selection judgment range of blender is as large as +-14 px. But if you want to modify it, you can only build a version yourself?

/13 It is better to change the judgment range to +-3 px. It seems that the range can be modified through python only.

/16 The poster wrote a .py script to achieve accurate selection, but did not publish it... I really need this to be reproduced...)

When making a selection, there are always redundant items that are selected together with the selection boundary if they are touched a little bit. 

It is too uncomfortable, and it is even more disastrous when the point, line and surface mode is fully turned on.

The point, line and surface editing mode of Metasequoia is fully turned on by default, but the selection result is quite accurate. There is a threshold for selection judgment.

3. The separated "edit switch" and "display switch" buttons of points, lines and surfaces

There is a display switch for points, lines and surfaces in the upper column of each view of Metasequoia. 

It is very convenient to preview when editing, and there is no need to switch back and forth between point, line and surface operation modes.

 4. When the cursor hovers over a point, line, or surface, it will be highlighted to prompt the selection judgment.

When the display of points, lines, and surfaces is turned off in Metasequoia, it will also be highlighted when hovering. It is conducive to precise adjustment.

Polyquilt also imitates this. But as mentioned above, there is no separate (select + adjust) function. When the modifier cover is turned on, the points, lines, and surfaces of the cover cannot be highlighted. It is still the original. Visually disconnected.

5. Select panel

Polyquilt imitates some functions of Metasequoia. Looking at the select function in the plan, I guess it is just to move Metasequoia's selection panel here? Maybe box and lasso selection options also added.

6. Manual sorting in the outliner view (object panel)

I can't understand why Blender can't do this. Unless one object has one collection?

**Comment by Dangry98** [comment]
Hi, thanks for the suggestions, but I think you posed this one the wrong repository. I think this one is the one you are looking for:
https://github.com/Dangry98/PolyQuilt-for-Blender-4.0/issues
